esphome:
  name: adafruit-matrixportal-s3
  friendly_name: Adafruit MatrixPortal S3

esp32:
  # Adafruit Matrix Portal S3
  # https://www.adafruit.com/product/5778
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "************************"

ota:
  password: "**************"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Adafruit-Matrixportal-S3"
    password: "**********"

captive_portal:

i2c:
  sda: GPIO16 # IO16
  scl: GPIO17 # IO17
  scan: true
  id: bus_a

# 64x64 matrices and is either connected to pin 8 or pin 16 of the HUB75 connector

# GPIO4   NEOPIX
# GPIO5   LIGHT
# GPIO6   UP
# GPIO7   DOWN
# GPIO16  SDA
# GPIO17  SCL

# Analog Connector/Pins labeled A1 through A4

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO4
    num_leds: 1
    name: "NeoPixel Light"

binary_sensor:
  - platform: gpio
    name: "BTN_UP"
    id: BTN_UP
    pin:
      number: GPIO6
      mode:
        input: true
        pullup: true
      inverted: true

  - platform: gpio
    name: "BTN_DOWN"
    id: BTN_DOWN
    pin:
      number: GPIO7
      mode:
        input: true
        pullup: true
      inverted: true
